name: Send Dependabot Security Alerts to DefectDojo

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFECTDOJO_PRODUCT_NAME: Owasp-juice-shop
  ENGAGEMENT_ID: 4

jobs:
  upload_dependabot_alerts:
    name: Import Dependabot alerts as GitHub Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Set repository details
        run: |
          OWNER="${GITHUB_REPOSITORY%%/*}"
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "OWNER=${OWNER}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Create GraphQL query file
        run: |
          cat <<EOF > query.graphql
          query {
            repository(name: "${REPO_NAME}", owner: "${OWNER}") {
              nameWithOwner
              url
              vulnerabilityAlerts(first: 100) {
                nodes {
                  id
                  number
                  createdAt
                  state
                  vulnerableManifestPath
                  vulnerableRequirements
                  securityVulnerability {
                    severity
                    package {
                      name
                      ecosystem
                    }
                    firstPatchedVersion {
                      identifier
                    }
                    vulnerableVersionRange
                    advisory {
                      summary
                      description
                      identifiers {
                        value
                        type
                      }
                      references {
                        url
                      }
                      cvss {
                        vectorString
                        score
                      }
                      cwes(first: 5) {
                        nodes {
                          cweId
                          name
                          description
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          EOF

      - name: Query GitHub GraphQL API for Dependabot alerts
        run: |
          gh api graphql --field query="$(cat query.graphql)" > dependabot-security-alerts.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECURITY_TOKEN }}

      - name: Upload Dependabot JSON to DefectDojo
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
            -F "product_name=${{ env.DEFECTDOJO_PRODUCT_NAME }}" \
            -F "engagement=${{ env.ENGAGEMENT_ID }}" \
            -F "scan_type=Github Vulnerability Scan" \
            -F "file=@dependabot-security-alerts.json" \
            -F "active=true" \
            -F "verified=true"
