name: 📦🚨 Send Dependabot Alerts to DefectDojo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  upload-dependabot-alerts:
    runs-on: self-hosted  # Use your internal runner that can reach DefectDojo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Dependabot Alerts from GitHub API
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_SECURITY_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
               -o raw-dependabot-alerts.json

      - name: Convert Dependabot Alerts to CSV for DefectDojo
        run: |
          python3 <<EOF
          import json
          import csv

          with open("raw-dependabot-alerts.json", "r") as f:
              alerts = json.load(f)

          with open("dependabot.csv", "w", newline='') as out:
              writer = csv.writer(out)
              writer.writerow(["Vulnerability ID", "Package", "Severity", "URL", "Summary"])

              for alert in alerts:
                  advisory = alert.get("security_advisory", {})
                  vuln = alert.get("security_vulnerability", {})
                  package = vuln.get("package", {})

                  writer.writerow([
                      advisory.get("ghsa_id", "N/A"),
                      package.get("name", "N/A"),
                      vuln.get("severity", "UNKNOWN"),
                      alert.get("html_url", ""),
                      advisory.get("summary", "")
                  ])
          EOF

      - name: Upload CSV to DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL_ngrok }}
          DD_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DD_API_TOKEN" \
            -F "engagement=4" \
            -F "scan_type=Generic Findings Import" \
            -F "file=@dependabot.csv" \
            -F "active=true" \
            -F "verified=true"
