name: Send Dependabot Alerts to DefectDojo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  send-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Dependabot Alerts
        env:
          GITHUB_TOKEN_FOR_ALERTS: ${{ secrets.GITHUB_TOKEN_FOR_ALERTS }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN_FOR_ALERTS" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Narsi-421/juice-shop/dependabot/alerts \
            -o dependabot-alerts.json

      - name: Upload Dependabot Alerts to DefectDojo
        env:
          DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -F 'file=@dependabot-alerts.json' \
            -F 'engagement=1' \
            -F 'scan_type=GitHub Vulnerability Scan' \
            -F 'active=true' \
            -F 'verified=true'
