name: Dependabot Alerts to DefectDojo

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  upload-dependabot:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Dependabot Alerts from GitHub
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_SECURITY_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
               -o raw-dependabot-alerts.json

      - name: Convert Dependabot Alerts to DefectDojo CSV Format
        run: |
          python3 <<EOF
          import json
          import csv

          with open("raw-dependabot-alerts.json") as f:
              alerts = json.load(f)

          with open("dependabot.csv", "w") as out:
              writer = csv.writer(out)
              writer.writerow([
                  "Title", "CWE ID", "Severity", "Description", "Mitigation",
                  "Impact", "References", "File Path", "Line Number", "Component Name", "Component Version"
              ])
              for alert in alerts:
                  advisory = alert.get("security_advisory", {})
                  vuln = alert.get("security_vulnerability", {})
                  package = vuln.get("package", {})

                  writer.writerow([
                      advisory.get("ghsa_id", "Dependabot Issue"),
                      "1035",  # CWE-1035: Placeholder for unknown
                      vuln.get("severity", "Medium").capitalize(),
                      advisory.get("summary", "No description provided."),
                      "Update to a patched version.",
                      "May lead to security vulnerabilities.",
                      advisory.get("references", [{}])[0].get("url", ""),
                      "", "",  # File path, Line number (optional)
                      package.get("name", ""),
                      package.get("ecosystem", "")
                  ])
          EOF

      - name: Upload CSV to DefectDojo
        env:
          DEFECTDOJO_URL: http://192.168.15.20:8080
          DD_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DD_API_TOKEN" \
            -F "engagement=4" \
            -F "scan_type=Generic Findings Import" \
            -F "file=@dependabot.csv" \
            -F "active=true" \
            -F "verified=true"
