name: Send Dependabot Alerts to DefectDojo (JSON)

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFECTDOJO_PRODUCT_NAME: Owasp-juice-shop
  DEFECTDOJO_URL_ngrok: ${{ secrets.DEFECTDOJO_URL_ngrok }}/api/v2
  ENGAGEMENT_ID: 4

jobs:
  upload_dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Set REPO_NAME
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Install GitHub CLI
        uses: cli/gh-action@v2

      - name: Fetch Dependabot Alerts via GraphQL
        run: |
          gh api graphql -F query='
            query {
              repository(owner: "${{ github.repository_owner }}", name: "${{ env.REPO_NAME }}") {
                vulnerabilityAlerts(first: 20) {
                  nodes {
                    createdAt
                    vulnerableManifestPath
                    securityVulnerability {
                      package { name }
                      vulnerableVersionRange
                      advisory {
                        severity
                        summary
                        description
                        references { url }
                        identifiers { type value }
                        cwes(first: 5) {
                          nodes {
                            cweId
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            }' > dependabot-raw.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECURITY_TOKEN }}

      - name: Upload JSON to DefectDojo
        run: |
          curl -X POST "${{ env.DEFECTDOJO_URL_ngrok }}/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
            -F "product_name=${{ env.DEFECTDOJO_PRODUCT_NAME }}" \
            -F "engagement=${{ env.ENGAGEMENT_ID }}" \
            -F "scan_type=Github Vulnerability Scan" \
            -F "file=@dependabot-raw.json" \
            -F "active=true" \
            -F "verified=true"
