name: Send Dependabot Alerts to DefectDojo

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFECTDOJO_PRODUCT_NAME: Owasp-juice-shop
  DEFECTDOJO_URL_ngrok: ${{ secrets.DEFECTDOJO_URL_ngrok }}/api/v2
  ENGAGEMENT_ID: 4

jobs:
  upload_dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Extract repository name
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Fetch Dependabot Alerts using REST API
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_SECURITY_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
               -o dependabot-raw.json

      - name: Upload raw JSON to DefectDojo using GitHub Vulnerability Scan
        run: |
          curl -X POST "${{ env.DEFECTDOJO_URL_ngrok }}/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
            -F "product_name=${{ env.DEFECTDOJO_PRODUCT_NAME }}" \
            -F "engagement=${{ env.ENGAGEMENT_ID }}" \
            -F "scan_type=Github Vulnerability Scan" \
            -F "file=@dependabot-raw.json" \
            -F "active=true" \
            -F "verified=true"
