name: Dependabot Alerts to DefectDojo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-dependabot-alerts:
    runs-on: self-hosted  # 👈 This is important! Runs on your internal runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Dependabot Alerts (example simulation)
        run: |
          echo '{ "alerts": [ { "package": "express", "severity": "HIGH", "details": "Example alert" } ] }' > dependabot-alerts.json

      - name: Upload Dependabot Alerts to DefectDojo
        env:
          DEFECTDOJO_URL: https://defectdojo.greytip.com
          DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}  
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -F "engagement=1" \
            -F "scan_type=Dependency Scan" \
            -F "active=true" \
            -F "verified=true" \
            -F "file=@dependabot-alerts.json"
