name:  Sending Dependabot Security Updates

on:
  workflow_dispatch:  # You can manually trigger it

permissions:
  contents: read

env:
  DEFECTDOJO_PRODUCT_NAME: Owasp-juice-shop
  DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}/api/v2
  ENGAGEMENT_ID: 4

jobs:
  import_dependabot_security_updates:
    name: Import Dependabot Security Updates
    runs-on: ubuntu-latest

    steps:
      - name: Extract Repository Name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Query Dependabot Alerts using GraphQL API
        run: |
          query='
          query {
            repository(owner: "${{ github.repository_owner }}", name: "${REPO_NAME}") {
              nameWithOwner
              url
              vulnerabilityAlerts(first: 100) {
                nodes {
                  id
                  number
                  createdAt
                  state
                  vulnerableManifestPath
                  vulnerableRequirements
                  securityVulnerability {
                    severity
                    package {
                      name
                    }
                    advisory {
                      summary
                      description
                      references {
                        url
                      }
                      identifiers {
                        type
                        value
                      }
                      cvss {
                        score
                        vectorString
                      }
                      cwes(first: 5) {
                        nodes {
                          cweId
                          name
                          description
                        }
                      }
                    }
                  }
                }
              }
            }
          }'

          echo "$query" > query.graphql

          gh api graphql --field query="$(cat query.graphql)" > dependabot-security-alerts.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECURITY_TOKEN }}

      - name: Upload to DefectDojo
        run: |
          curl -X POST "${DEFECTDOJO_URL}/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
            -F "product_name=${DEFECTDOJO_PRODUCT_NAME}" \
            -F "engagement=${ENGAGEMENT_ID}" \
            -F "scan_type=Github Vulnerability Scan" \
            -F "file=@dependabot-security-alerts.json" \
            -F "active=true" \
            -F "verified=true"
