name: 🛡️ Upload Dependabot Alerts to DefectDojo

on:
  workflow_dispatch:  # ✅ Allows manual triggering

env:
  DEFECTDOJO_PRODUCT_NAME: Owasp-juice-shop
  ENGAGEMENT_ID: 4
  DEFECTDOJO_URL: http://192.168.15.20:8080/api/v2  # ✅ Your self-hosted DefectDojo API

jobs:
  upload_dependabot_alerts:
    runs-on: self-hosted  # ✅ Important if using internal server

    steps:
      - name: Fetch Dependabot Alerts from GitHub API
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
               -o raw-dependabot-alerts.json

      - name: Convert JSON to CSV for DefectDojo
        run: |
          python3 <<EOF
          import json, csv
          with open("raw-dependabot-alerts.json") as f:
              alerts = json.load(f)
          with open("dependabot.csv", "w") as out:
              writer = csv.writer(out)
              writer.writerow(["Vulnerability ID", "Package", "Severity", "URL", "Summary"])
              for alert in alerts:
                  writer.writerow([
                      alert.get("security_advisory", {}).get("ghsa_id", "N/A"),
                      alert.get("security_vulnerability", {}).get("package", {}).get("name", "N/A"),
                      alert.get("security_vulnerability", {}).get("severity", "UNKNOWN"),
                      alert.get("html_url", ""),
                      alert.get("security_advisory", {}).get("summary", "")
                  ])
          EOF

      - name: Upload CSV to DefectDojo
        run: |
          curl -X POST "${{ env.DEFECTDOJO_URL }}/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
            -F "product_name=${{ env.DEFECTDOJO_PRODUCT_NAME }}" \
            -F "engagement=${{ env.ENGAGEMENT_ID }}" \
            -F "scan_type=Generic Findings Import" \
            -F "file=@dependabot.csv" \
            -F "active=true" \
            -F "verified=true"
