name: Dependabot Alerts to DefectDojo

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:      # Also allows manual triggering

jobs:
  upload-dependabot:
    runs-on: self-hosted  # Must run on a self-hosted runner with network access to DefectDojo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Dependabot Alerts from GitHub
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_SECURITY_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
               -o raw-dependabot-alerts.json

      - name: Convert Dependabot Alerts to DefectDojo CSV Format
        run: |
          python3 <<EOF
          import json
          import csv

          with open("raw-dependabot-alerts.json") as f:
              alerts = json.load(f)

          with open("dependabot.csv", "w") as out:
              writer = csv.writer(out)
              writer.writerow(["Vulnerability ID", "Package", "Severity", "URL", "Summary"])
              for alert in alerts:
                  writer.writerow([
                      alert.get("security_advisory", {}).get("ghsa_id", "N/A"),
                      alert.get("security_vulnerability", {}).get("package", {}).get("name", "N/A"),
                      alert.get("security_vulnerability", {}).get("severity", "UNKNOWN"),
                      alert.get("html_url", ""),
                      alert.get("security_advisory", {}).get("summary", "")
                  ])
          EOF

      - name: Upload CSV to DefectDojo
        env:
          DEFECTDOJO_URL: http://192.168.15.20:8080
          DD_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DD_API_TOKEN" \
            -F "engagement=4" \
            -F "scan_type=Generic Findings Import" \
            -F "file=@dependabot.csv" \
            -F "active=true" \
            -F "verified=true"
